# FROM ubuntu:14.04
# RUN sudo apt-get -y install oracle-java8-installer
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

# echo "wget installed"
# now install jenkins
RUN sudo wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
RUN sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN sudo apt-get update
RUN sudo apt-get -y install jenkins
# RUN sudo apt-get -y install junit
EXPOSE 8080
RUN sudo service jenkins start
